---
# The variables file used by the playbooks
# in the db role for environment production.

# mysqld
mysqlservice: mysqld
mysql_port: 43309
datadir: /var/lib/mysql
mysql_unix_socket: /var/run/mysqld/mysqld.sock
performance_schema: off

# logging
db_log_dir: /var/log/mysql
db_service_log: mysqld.log
db_general_log: OFF
db_general_log_file: mysqld-general.log
db_slow_query_log: OFF
db_slow_query_log_file: mysqld-slow.log
db_long_query_time: 5
db_log_slow_admin_statements: OFF
db_log_slow_slave_statements: OFF
db_audit_log: OFF
